export const AUTH_START = 'AUTH_START';
export const AUTH_SUCCESS = 'AUTH_SUCCESS';
export const AUTH_FAIL = 'AUTH_FAIL';
export const AUTH_LOGOUT = 'AUTH_LOGOUT';

export const FETCH_LOCATIONS_START='FETCH_LOCATIONS_START';
export const FETCH_LOCATIONS_FAIL='FETCH_LOCATIONS_FAIL';
export const FETCH_LOCATIONS_SUCCESS='FETCH_LOCATIONS_SUCCESS';

export const SAVE_LOCATION_SUCCESS = 'SAVE_LOCATION_SUCCESS';
export const SAVE_LOCATION_FAIL = 'SAVE_LOCATION_FAIL';

export const FETCH_COUNTRY_START = 'FETCH_COUNTRY_START';
export const FETCH_COUNTRY_SUCCESS = 'FETCH_COUNTRY_SUCCESS';
export const FETCH_COUNTRY_FAIL = 'FETCH_COUNTRY_FAIL';

export const ADD_TASK = 'ADD_TASK';
export const UPDATE_TASK = 'UPDATE_TASK';
export const DELETE_TASK = 'DELETE_TASK';
export const UPDATE_GRID = 'UPDATE_GRID';