export const AUTH_START = 'AUTH_START';
export const AUTH_SUCCESS = 'AUTH_SUCCESS';
export const AUTH_FAIL = 'AUTH_FAIL';
export const AUTH_LOGOUT = 'AUTH_LOGOUT';

export const SAVE_LOCATION_SUCCESS = 'SAVE_LOCATION_SUCCESS';
export const SAVE_LOCATION_FAIL = 'SAVE_LOCATION_FAIL';

export const SEARCH_SONG_START = 'SEARCH_SONG';
export const SEARCH_SONG_SUCCESS = 'SEARCH_SONG_SUCCESS';
export const SEARCH_SONG_FAIL = 'SEARCH_SONG_FAIL';

export const SAVE_SONG_START = 'SAVE_SONG_START';
export const SAVE_SONG_SUCCESS = 'SAVE_SONG_SUCCESS';
export const SAVE_SONG_FAIL = 'SAVE_SONG_FAIL';
export const SAVE_SONG_FORGET = 'SAVE_SONG_FORGET';

export const AUTHENTICATE = 'AUTHENTICATE';
export const SPOTIFY_LOGOUT = 'SPOTIFY_LOGOUT';
export const FETCH_SONG_START = 'FETCH_SONG_START';
export const FETCH_SONG_FAIL = 'FETCH_SONG_FAIL';
export const FETCH_SONG_SUCCESS = 'FETCH_SONG_SUCCESS';